site_name: route53-dynamic-dns
site_description: Update AWS Route53 hosted zone with current public IP address. Alternative to Dynamic DNS services such as Dyn, No-IP, etc
site_author: sjmayotte
site_url: https://sjmayotte.dev/route53-dynamic-dns/
edit_uri: edit/master/docs/
docs_dir: docs

repo_name: sjmayotte/route53-dynamic-dns
repo_url: https://github.com/sjmayotte/route53-dynamic-dns

#extra:
  #seo:
    #google: 
    #bing: 
    #alexa:
    #yandex:

nav:
  - Home: index.md
  - Installation:
    - Docker: install/docker.md
    - Node Process: install/node.md
  - Usage:
    - Docker: usage/docker.md
    - Node Process: usage/node.md
    - Logs: usage/logs.md
  - Configuration:
    - Environment Variables: config/env.md
    - AWS Services: config/aws.md
  - FAQ: faq.md
  - Reporting an issue: issues.md
  - Contributing: contributing.md