name: Docker Image CI

on:
  push:
    branches: [ master ]
    
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build & Test Code

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        
    - run: npm ci
      
    - run: npm run build --if-present
      
    - run: npm test

  docker:
    name: Build Docker Container

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date --utc +'%Y-%m-%dT%H:%M:%SZ')"
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sjmayotte/route53-dynamic-dns:latest
        build-args: |
            GIT_SHA=$GITHUB_SHA
            BUILD_DATE=${{ steps.date.outputs.date }}
            DOCKER_TAG=1.1
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
